export enum ActionTypes {
    SEARCH_REPOSITORIES= 'SEARCH_REPOSITORIES',
    SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
    SEARCH_REPOSITORIES_FAIL = 'SEARCH_REPOSITORIES_FAIL',
    SET_SEARCH_INPUT = 'SET_SEARCH_INPUT',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
}
